cadmin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^', include('web.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url

from web.views import *
from web.user_views import *
from web.customers_views import *


urlpatterns = [

    # customer fronted views
    url(r'^$', HomeListView.as_view(), name='fe_home'),

    url(r'^customer-file/(?P<id>\d+)/$', FileDetailView.as_view(), name='fe_file'),
    url(r'^customer-files/$', HomeFilesListView.as_view(), name='fe_files'),
    url(r'^customer-audio/$', HomeAudioListView.as_view(), name='fe_audio'),
    url(r'^customer-video/$', HomeVideoListView.as_view(), name='fe_video'),
    url(r'^customer-bin/$', HomeBinaryListView.as_view(), name='fe_bin'),

    url(r'^customer-reviews/(?P<id>\d+)/$', HomeReviewsListView.as_view(), name='fe_reviews'),
    url(r'^customer-reviews-add/(?P<id>\d+)/$', HomeReviewAddView.as_view(), name='fe_review_add'),

    url(r'^customer-login/$', HomeLoginView.as_view(), name='fe_login'),
    url(r'^customer-logout/$', HomeLogoutView.as_view(), name='fe_logout'),

    url(r'^customer-order/2/(?P<id>\d+)/$', OrderView2.as_view(), name='fe_order_2'),
    url(r'^customer-order/3/(?P<id>\d+)/$', OrderView3.as_view(), name='fe_order_3'),
    url(r'^customer-order/4/(?P<id>\d+)/$', OrderView4.as_view(), name='fe_order_4'),

    # admin views
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # features
    url(r'^features/$', FeaturesListView.as_view(), name='features'),
    url(r'^features/add/$', FeatureAddView.as_view(), name='features_add'),
    url(r'^features/edit/(?P<id>\d+)/$', FeatureEditView.as_view(), name='features_edit'),
    url(r'^features/delete/(?P<id>\d+)$', FeatureDeleteView.as_view(), name='features_delete'),

    # orders
    url(r'^orders/$', OrdersListView.as_view(), name='orders'),
    url(r'^orders/add/$', OrdersAddView.as_view(), name='orders_add'),
    url(r'^orders/edit/(?P<id>\d+)/$', OrdersEditView.as_view(), name='orders_edit'),
    url(r'^orders/delete/(?P<id>\d+)$', OrdersDeleteView.as_view(), name='orders_delete'),

    # room features
    url(r'^room-features/$', RoomFeaturesListView.as_view(), name='room_features'),
    url(r'^room-features/add/$', RoomFeatureAddView.as_view(), name='room_features_add'),
    url(r'^room-features/edit/(?P<id>\d+)/$', RoomFeatureEditView.as_view(), name='room_features_edit'),
    url(r'^room-features/delete/(?P<id>\d+)$', RoomFeatureDeleteView.as_view(), name='room_features_delete'),

    # rooms
    url(r'^rooms/(?P<p_id>\d+)/$', RoomsListView.as_view(), name='rooms'),
    url(r'^rooms/(?P<p_id>\d+)/add/$', RoomAddView.as_view(), name='rooms_add'),
    url(r'^rooms/(?P<p_id>\d+)/edit/(?P<id>\d+)/$', RoomEditView.as_view(), name='rooms_edit'),
    url(r'^rooms/(?P<p_id>\d+)/delete/(?P<id>\d+)/$', RoomDeleteView.as_view(), name='rooms_delete'),

    # rest places
    url(r'^places/$', RestPlacesListView.as_view(), name='places'),
    url(r'^places/add/$', RestPlacesAddView.as_view(), name='places_add'),
    url(r'^places/edit/(?P<id>\d+)/$', RestPlacesEditView.as_view(), name='places_edit'),
    url(r'^places/delete/(?P<id>\d+)/$', RestPlacesDeleteView.as_view(), name='places_delete'),

    # reviews
    url(r'^reviews/$', ReviewsListView.as_view(), name='reviews'),
    url(r'^reviews/add/$', ReviewAddView.as_view(), name='reviews_add'),
    url(r'^reviews/edit/(?P<id>\d+)/$', ReviewEditView.as_view(), name='reviews_edit'),
    url(r'^reviews/delete/(?P<id>\d+)/$', ReviewDeleteView.as_view(), name='reviews_delete'),

    # files
    url(r'^files/$', FilesListView.as_view(), name='files'),
    url(r'^files/add/$', FilesAddView.as_view(), name='files_add'),
    url(r'^files/edit/(?P<id>\d+)/$', FilesEditView.as_view(), name='files_edit'),
    url(r'^files/delete/(?P<id>\d+)$', FilesDeleteView.as_view(), name='files_delete'),

    # users
    url(r'^users/$', UsersListView.as_view(), name='users'),
    url(r'^users/edit/(?P<id>\d+)/$', UsersEditView.as_view(), name='users_edit'),
    url(r'^users/add/$', UsersAddView.as_view(), name='users_add'),
    url(r'^users/delete/(?P<id>\d+)$', UsersDeleteView.as_view(), name='users_delete'),

    url(r'^folders/$', FoldersListView.as_view(), name='folders'),
    url(r'^video/$', VideoListView.as_view(), name='video'),

]

web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import random
import string
import os
from datetime import datetime

from django.db import models
from django.db.models import Avg

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager

from django.core.cache import cache

from web.constants import *


class AuthManager(BaseUserManager):

    def create_user(self, email, password, first_name, last_name, **extra_fields):
        user = self.model(email=self.normalize_email(email), first_name=first_name,
            last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, first_name, last_name, **extra_fields):
        return self.create_user(email, password, first_name, last_name, is_admin=True, **extra_fields)


class User(AbstractBaseUser):
    USERNAME_FIELD = 'email'
    objects = AuthManager()

    email = models.EmailField(unique=True, null=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    type = models.IntegerField(choices=USER_TYPE_E, default=2)

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def public_name(self):
        return "%s" % (self.first_name)

    @property
    def is_admin_user(self):
        return self.type == 1


class File(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('Folder', null=True, blank=True)
    type = models.IntegerField(choices=FILE_TYPE_E, default=1)
    owner = models.ForeignKey('User')

    top_content = models.TextField(null=True, blank=True)
    middle_content = models.TextField(null=True, blank=True)
    bottom_content = models.TextField(null=True, blank=True)

    top_slider = models.ForeignKey('ImageSlider', null=True, blank=True, related_name='top_slider')
    bottom_slider = models.ForeignKey('ImageSlider', null=True, blank=True, related_name='bottom_slider')

    features = models.ManyToManyField('Feature')

    def __unicode__(self):
        return "%s" % (self.name)

    @property
    def latest_reviews(self):
        return self.review_set.all().order_by('-id')[:3]

    @property
    def rate(self):
        cache_key = 'file_rate_%s' % (self.id)
        rate = cache.get(cache_key)
        if not rate:
            rate = Review.objects.filter(item=self).aggregate(Avg('rate')).get('rate__avg')
            cache.set(cache_key, rate)
        return rate

    @property
    def reviews_count(self):
        cache_key = 'file_reviews_count_%s' % (self.id)
        rcount = cache.get(cache_key)
        if not rcount:
            rcount = Review.objects.filter(item=self).count()
            cache.set(cache_key, rcount)
        return rcount

    @property
    def rooms(self):
        return self.room_set.all()

    @property
    def similar(self):
        return File.objects.exclude(id=self.id).annotate(
            Avg('review__rate')).order_by('-review__rate__avg')[:5]


def feature_upload_path(instance, filename):
    rnd_part = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(4))
    path = 'uploads/features/feature_{0}{1}'.format(rnd_part, filename[-4:])

    try:
        os.makedirs(path)
    except Exception as e:
        pass
    return path


class RestPlace(models.Model):
    name = models.TextField()
    image = models.FileField(null=True, blank=True, upload_to=feature_upload_path)
    count = models.IntegerField(default=1)

    def __unicode__(self):
        return "%s" % (self.name)


class RoomFeature(models.Model):
    name = models.TextField()
    image = models.FileField(null=True, blank=True, upload_to=feature_upload_path)

    def __unicode__(self):
        return "%s" % (self.name)


class Room(models.Model):
    item = models.ForeignKey('File')
    name = models.TextField()
    users_count = models.IntegerField(default=1)
    count = models.IntegerField(default=1)

    images = models.ManyToManyField('SliderImage', blank=True)
    features = models.ManyToManyField('RoomFeature')
    rest_places = models.ManyToManyField('RestPlace')
    prices = models.ManyToManyField('RoomPrice')

    def get_prices_desc(self):
        return self.prices.order_by('-people_number', '-price')

    def get_prices_asc(self):
        return self.prices.order_by('people_number', 'price')

    def __unicode__(self):
        return "%s" % (self.name)


class RoomPrice(models.Model):
    people_number = models.IntegerField(default=1)
    price = models.FloatField(default=0)

    def __unicode__(self):
        return "%s for %s guests" % (self.price, self.people_number)


class Order(models.Model):
    item = models.ForeignKey('File')
    rooms = models.ManyToManyField('Room')
    user = models.ForeignKey('User', blank=True, null=True)

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    price = models.FloatField(default=0)

    title = models.IntegerField(choices=TITLES_E, default=1)
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    message = models.TextField()


class Review(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    rate = models.FloatField(default=0)
    user = models.ForeignKey('User')
    item = models.ForeignKey('File')
    pros = models.TextField(null=True, blank=True)
    cons = models.TextField(null=True, blank=True)
    heading = models.TextField()
    type = models.IntegerField(choices=TRIP_TYPE_E, default=1)


class Feature(models.Model):
    name = models.CharField(max_length=200)
    is_main = models.BooleanField(default=False)
    key = models.CharField(max_length=10)
    image = models.FileField(null=True, blank=True, upload_to=feature_upload_path)

    def __unicode__(self):
        return "%s" % (self.name)


class ImageSlider(models.Model):
    images = models.ManyToManyField('SliderImage', blank=True)


def image_upload_path(instance, filename):
    now = datetime.now()
    rnd_part = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(4))

    path = 'uploads/{0}/{1}/{2}/img_{3}{4}'.format(
        now.year, now.month, now.day, rnd_part, filename[-4:])

    try:
        os.makedirs(path)
    except Exception as e:
        pass

    return path


class SliderImage(models.Model):
    image = models.FileField(upload_to=image_upload_path)


class Folder(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey('Folder', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

web/templates/files/_files_list.html
{% for object in objects %}
<tr>
    <td>{{ object.name }}</td>
    <td>{{ object.created_at }}</td>
    <td>{{ object.get_type_display }}</td>
    <td>
        <a class="list-option" href="{% url 'files_edit' id=object.id %}"><i class="material-icons">edit</i></a>
        <a class="list-option" href="{% url 'files_delete' id=object.id %}" onclick="return confirm('Please confirm {{ object.name }} deletion?')">
            <i class="material-icons">delete</i>
        </a>
    </td>
</tr>
{% endfor %}

web/templates/files/files_add.html
{% extends "files/files_edit.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block title %}Files Add{% endblock %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Files" "files" %}
    {% breadcrumb "Add files" "" %}
{% endblock %}

{% block content %}
    {{ block.super }}
{% endblock %}

web/templates/files/files_edit.html
{% extends "base.html" %}

{% load widget_tweaks %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Files Edit{% endblock %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "files" %}
    {% breadcrumb "Files" "files" %}
    {% breadcrumb "Edit files" "" %}
{% endblock %}

{% block content %}

<div class="col-xs-8">
    <div class="row">
        {% if not '/add' in request.path %}
            <a href="{% url 'rooms' p_id=form.instance.id %}">Rooms</a>
        {% endif %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% include "common/_form_nf_errors.html" %}

            {% for field in form %}

                {% include "common/_form_field_errors.html" %}

                <div class="form-label">{{ field.label }}</div>
                {{ field|add_class:"form-control" }}

                {% if field.name == 'top_images' and form.instance.top_slider.images.all %}
                    <div class="slider_images">
                        {% for img in form.instance.top_slider.images.all %}
                        <img src="{{ img.image.url }}"></img>
                        {% endfor %}
                    </div>
                {% elif field.name == 'bottom_images' and form.instance.bottom_slider.images.all%}
                    <div class="slider_images">
                        {% for img in form.instance.bottom_slider.images.all %}
                        <img src="{{ img.image.url }}"></img>
                        {% endfor %}
                    </div>
                {% endif %}

            {% endfor %}

            <div class="btn-container">
                <input class="btn btn-bold btn-default" type="submit" value="Update" />
                <a role="button" class="btn btn-bold btn-danger" href="{% url 'files' %}">Cancel</a>
            </div>

        </form>
    </div>
</div>

{% endblock %}

web/templates/files/files_list.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Files{% endblock %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "/" %}
    {% breadcrumb "Files" "" %}
{% endblock %}

{% block content %}

<div class="item_actions">
    <a role="button" class="btn btn-bold btn-default" href="{% url 'files_add' %}">Add</a>
</div>

<table class="list-table">
    <thead>
        <tr>
            <th class="sortable" data-field='name'>Name</th>
            <th class="sortable" data-field='created'>Created</th>
            <th class="sortable" data-field='type'>Type</th>
            <th class="">Options<th>
        </tr>
        <tr>
            <th><input class='form-control filter keyup' data-field='name'></input></th>
            <th><input class='form-control filter change datepicker' data-field='created'></input></th>
            <th><select class='filter change selectpicker' data-field='type'>
                <option value="0">--</option>
                <option value="1">TXT</option>
                <option value="2">AUDIO</option>
                <option value="3">VIDEO</option>
                <option value="4">BINARY</option>
            </select></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% include 'files/_files_list.html' %}
    </tbody>
</table>

{% include 'common/_pagin.html' %}

<script>
    listURL="{{ list_url }}";
</script>

{% endblock %}

web/templates/files/list.html
{% extends "base.html" %}

{% block title %}Files{% endblock %}

{% block content %}

<h2> Hello files </h2>

{% for file in files %}
<h2>
    {{ file.name }}
</h2>
{% endfor %}

{% endblock %}