cadmin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^', include('web.urls')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url

from web.views import *
from web.user_views import *
from web.customers_views import *


urlpatterns = [

    # customer fronted views
    url(r'^$', HomeListView.as_view(), name='fe_home'),

    url(r'^customer-file/(?P<id>\d+)/$', FileDetailView.as_view(), name='fe_file'),
    url(r'^customer-files/$', HomeFilesListView.as_view(), name='fe_files'),
    url(r'^customer-audio/$', HomeAudioListView.as_view(), name='fe_audio'),
    url(r'^customer-video/$', HomeVideoListView.as_view(), name='fe_video'),
    url(r'^customer-bin/$', HomeBinaryListView.as_view(), name='fe_bin'),

    url(r'^customer-reviews/(?P<id>\d+)/$', HomeReviewsListView.as_view(), name='fe_reviews'),
    url(r'^customer-reviews-add/(?P<id>\d+)/$', HomeReviewAddView.as_view(), name='fe_review_add'),

    url(r'^customer-login/$', HomeLoginView.as_view(), name='fe_login'),
    url(r'^customer-logout/$', HomeLogoutView.as_view(), name='fe_logout'),

    url(r'^customer-order/2/(?P<id>\d+)/$', OrderView2.as_view(), name='fe_order_2'),
    url(r'^customer-order/3/(?P<id>\d+)/$', OrderView3.as_view(), name='fe_order_3'),
    url(r'^customer-order/4/(?P<id>\d+)/$', OrderView4.as_view(), name='fe_order_4'),

    # admin views
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # features
    url(r'^features/$', FeaturesListView.as_view(), name='features'),
    url(r'^features/add/$', FeatureAddView.as_view(), name='features_add'),
    url(r'^features/edit/(?P<id>\d+)/$', FeatureEditView.as_view(), name='features_edit'),
    url(r'^features/delete/(?P<id>\d+)$', FeatureDeleteView.as_view(), name='features_delete'),

    # orders
    url(r'^orders/$', OrdersListView.as_view(), name='orders'),
    url(r'^orders/add/$', OrdersAddView.as_view(), name='orders_add'),
    url(r'^orders/edit/(?P<id>\d+)/$', OrdersEditView.as_view(), name='orders_edit'),
    url(r'^orders/delete/(?P<id>\d+)$', OrdersDeleteView.as_view(), name='orders_delete'),

    # room features
    url(r'^room-features/$', RoomFeaturesListView.as_view(), name='room_features'),
    url(r'^room-features/add/$', RoomFeatureAddView.as_view(), name='room_features_add'),
    url(r'^room-features/edit/(?P<id>\d+)/$', RoomFeatureEditView.as_view(), name='room_features_edit'),
    url(r'^room-features/delete/(?P<id>\d+)$', RoomFeatureDeleteView.as_view(), name='room_features_delete'),

    # rooms
    url(r'^rooms/(?P<p_id>\d+)/$', RoomsListView.as_view(), name='rooms'),
    url(r'^rooms/(?P<p_id>\d+)/add/$', RoomAddView.as_view(), name='rooms_add'),
    url(r'^rooms/(?P<p_id>\d+)/edit/(?P<id>\d+)/$', RoomEditView.as_view(), name='rooms_edit'),
    url(r'^rooms/(?P<p_id>\d+)/delete/(?P<id>\d+)/$', RoomDeleteView.as_view(), name='rooms_delete'),

    # rest places
    url(r'^places/$', RestPlacesListView.as_view(), name='places'),
    url(r'^places/add/$', RestPlacesAddView.as_view(), name='places_add'),
    url(r'^places/edit/(?P<id>\d+)/$', RestPlacesEditView.as_view(), name='places_edit'),
    url(r'^places/delete/(?P<id>\d+)/$', RestPlacesDeleteView.as_view(), name='places_delete'),

    # reviews
    url(r'^reviews/$', ReviewsListView.as_view(), name='reviews'),
    url(r'^reviews/add/$', ReviewAddView.as_view(), name='reviews_add'),
    url(r'^reviews/edit/(?P<id>\d+)/$', ReviewEditView.as_view(), name='reviews_edit'),
    url(r'^reviews/delete/(?P<id>\d+)/$', ReviewDeleteView.as_view(), name='reviews_delete'),

    # files
    url(r'^files/$', FilesListView.as_view(), name='files'),
    url(r'^files/add/$', FilesAddView.as_view(), name='files_add'),
    url(r'^files/edit/(?P<id>\d+)/$', FilesEditView.as_view(), name='files_edit'),
    url(r'^files/delete/(?P<id>\d+)$', FilesDeleteView.as_view(), name='files_delete'),

    # users
    url(r'^users/$', UsersListView.as_view(), name='users'),
    url(r'^users/edit/(?P<id>\d+)/$', UsersEditView.as_view(), name='users_edit'),
    url(r'^users/add/$', UsersAddView.as_view(), name='users_add'),
    url(r'^users/delete/(?P<id>\d+)$', UsersDeleteView.as_view(), name='users_delete'),

    url(r'^folders/$', FoldersListView.as_view(), name='folders'),
    url(r'^video/$', VideoListView.as_view(), name='video'),

]

web/forms.py
# -*- coding: utf-8 -*-

from django.core.validators import validate_email
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.conf import settings
from django.forms import formset_factory

from web.models import *


class SaveFileMixin(object):
    def save_slider_files(self, files):
        if files:
            slider = ImageSlider.objects.create()

            for file in files:
                image = SliderImage.objects.create(image=file)
                slider.images.add(image)

            return slider


class AuthForm(AuthenticationForm):

    def clean(self):
        cd = super(AuthForm, self).clean()
        email = cd.get('username', None)
        if email:
            validate_email(email)


class FileEditForm(forms.ModelForm, SaveFileMixin):

    top_images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    bottom_images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = File
        fields = ['name', 'type', 'owner', 'features', 'top_content', 'middle_content', 'bottom_content']

        widgets = {
            'top_content': forms.Textarea(attrs={'class': 'tinymce'}),
            'middle_content': forms.Textarea(attrs={'class': 'tinymce'}),
            'bottom_content': forms.Textarea(attrs={'class': 'tinymce'}),
        }

    def save(self, commit=True):
        instance = super(FileEditForm, self).save(commit=commit)

        if self.files:
            instance.top_slider = self.save_slider_files(self.files.getlist('top_images'))
            instance.bottom_slider = self.save_slider_files(self.files.getlist('bottom_images'))
            instance.save()

        return instance


class UserEditForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ['is_active', 'first_name', 'last_name', 'type', 'email']


class UserAddForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ['is_active', 'email', 'first_name', 'last_name', 'type']


class FeatureEditForm(forms.ModelForm):

    class Meta:
        model = Feature
        fields = ['name', 'is_main', 'image']

        widgets = {
            'image': forms.FileInput(),
        }


class RoomFeatureEditForm(forms.ModelForm):

    class Meta:
        model = RoomFeature
        fields = ['name', 'image']

        widgets = {
            'image': forms.FileInput(),
        }


class FEReviewEditForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['heading', 'rate', 'pros', 'cons']

        widgets = {
            'heading': forms.Textarea(attrs={'class': 'tinymce'}),
            'pros': forms.Textarea(attrs={'class': 'tinymce'}),
            'cons': forms.Textarea(attrs={'class': 'tinymce'}),
        }


class FEOrderForm(forms.ModelForm):

    confirm_email = forms.EmailField()

    class Meta:
        model = Order
        fields = ['title', 'first_name', 'last_name', 'email', 'message']

    def clean(self):
        cd = super(FEOrderForm, self).clean()
        if cd['email'] != cd['confirm_email']:
            msg = "Email and email confirmation have to match!"
            self.add_error('confirm_email', msg)
            raise forms.ValidationError(msg)
        return cd

    #item = models.ForeignKey('File')
    #room = models.ForeignKey('Room')
    #user = models.ForeignKey('User', blank=True, null=True)

    #start_date = models.DateTimeField()
    #end_date = models.DateTimeField()

    #title = forms.ChoiceField(choices=((0, ''), (1, 'Mr.'), (2, 'Ms.'), (3, 'Mrs.')), label="Title")
    #message = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))


class ReviewEditForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['heading', 'rate', 'pros', 'cons', 'user', 'item']

        widgets = {
            'heading': forms.Textarea(attrs={'class': 'tinymce'}),
            'pros': forms.Textarea(attrs={'class': 'tinymce'}),
            'cons': forms.Textarea(attrs={'class': 'tinymce'}),
        }


class RoomPriceForm(forms.ModelForm):
    class Meta:
        model = RoomPrice
        fields = ['price', 'people_number']


class RoomEditForm(forms.ModelForm):

    room_images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Room
        fields = ['name', 'prices', 'users_count', 'count', 'features', 'room_images', 'rest_places']

        widgets = {
            'name': forms.TextInput(),
        }

    def __init__(self, *args, **kwargs):
        super(RoomEditForm, self).__init__(*args, **kwargs)
        self.fields['prices'].queryset = RoomPrice.objects.filter(room__id=self.instance.id)
        self.prices_formset = formset_factory(RoomPriceForm, extra=2)

    def clean(self, *args, **kwargs):
        cd = super(RoomEditForm, self).clean(*args, **kwargs)
        pf = self.prices_formset(self.data)
        pf.is_valid()
        return cd

    def save(self, commit=True):
        instance = super(RoomEditForm, self).save(commit=commit)

        if self.files:
            instance.images.all().delete()
            for file in self.files.getlist('room_images'):
                image = SliderImage.objects.create(image=file)
                instance.images.add(image)

        pf = self.prices_formset(self.data)

        for form in pf:
            prices_instance = form.save()
            if prices_instance.price and prices_instance.people_number:
                instance.prices.add(prices_instance)
            else:
                prices_instance.delete()

        return instance


class OrderEditForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['item', 'rooms', 'user', 'start_date', 'end_date']

    def __init__(self, *args, **kwargs):
        super(OrderEditForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['end_date'].input_formats = settings.DATE_INPUT_FORMATS


class RestPlacesEditForm(forms.ModelForm):

    class Meta:
        model = RestPlace
        fields = ['name', 'image', 'count']

        widgets = {
            'name': forms.TextInput(),
        }

web/templates/customers/_files_list.html
{% load thumbnail %}

{% for object in objects %}
    {% if object.type == 1 %}
    <div class="box">
        <div class='columns {{ object.get_type_display }}'>
            <div class="column is-half">
                <div class='carousel carousel-animated carousel-animate-slide list-icons'>
                    <div class='carousel-container'>
                        {% for img in object.top_slider.images.all %}
                            <div class='carousel-item has-background is-active'>
                                <a href="{% url 'fe_file' id=object.id %}">
                                {% thumbnail img.image "320x256" crop="center" as im %}
                                    <img class="is-background" src="{{ im.url }}" width="220" height="180"></img>
                                </a>
                                {% endthumbnail %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="carousel-navigation is-overlay">
                        <div class="carousel-nav-left">
                            <i class="fa fa-chevron-left" aria-hidden="true"></i>
                        </div>
                        <div class="carousel-nav-right">
                            <i class="fa fa-chevron-right" aria-hidden="true"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="columns column is-multiline">
                <div class="column is-two-thirds">
                    <a href="{% url 'fe_file' id=object.id %}" class="subtitle is-4">{{ object.name }}</a>
                    <br>
                    <a class="modal-button subtitle is-6" data-target="modal-map"
                        data-title="{{ object.name }}">
                        Location map <i class="fas fa-map-marker-alt"></i></a>
                </div>
                <div class="column is-one-third has-text-right">
                    <div class="icon rate-avg">{{ object.rate|floatformat }}</div>
                    <div class="">{{ object.reviews_count }} reviews</div>
                    <a class="button is-link" href="{% url 'fe_file' id=object.id %}">More info</a>
                </div>
                <div class="column">
                    {{ object.middle_content|safe }}
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="box">
        <div class='columns {{ object.get_type_display }}'>
            <div class="column">{{ object.name }}</div>
            <div class="column">{{ object.created_at }}</div>
        </div>
    </div>
    {% endif %}
{% endfor %}

web/templates/customers/_left_filters.html
{% if not request.get_full_path == '/' and request.session.start_date %}

<div class="box">
    <header class=""><strong>Search Dates</strong></header>
    <br>
    <header class=""><strong>Start Date</strong></header>
    <header>{{ request.session.start_date }}</header>
    <header class=""><strong>End Date</strong></header>
    <header>{{ request.session.end_date }}</header>
    <header class=""><strong>People Number</strong></header>
    <header>{{ request.session.guest_number }}</header>
    <header class=""><strong>Rooms Number</strong></header>
    <header>{{ request.session.rooms_number }}</header>
    <br>
    {% if request.session.features %}
        <header><strong>Features</strong></header>
        <header>{{ request.session.features|safe }}</header>
    {% endif %}
    {% if request.session.room_features %}
        <header><strong>Room Features</strong></header>
        <header>{{ request.session.room_features|safe }}</header>
    {% endif %}
    {% if request.session.rates %}
        <header><strong>Ratings</strong></header>
        <header>{{ request.session.rates|safe }}</header>
        <br>
    {% endif %}
    <div style="display:inline-block;width:100%">
        <a href="{% url 'fe_home' %}" class="button pull-right is-warning">Change search</a>
    </div>
</div>

{% else %}

<div class="box">
    <header class=""><strong>Dates search</strong></header>

    <header class="">Start date</header>
    <input class="input is-small filter" name="start_date" id="id-start-date"
        type="text" data-field="start_date"></input>

    <header class="">End date</header>
    <input class="input is-small filter" name="end_date" id="id-end-date"
        type="text" data-field="end_date"></input>

    <div>
        <header class="">Guests number</header>
        <div class="select is-small">
            <select class="filter" name="guest_number" data-field="guest_number">
                <option value='1'>1</option>
                <option value='2' selected>2</option>
                <option value='3'>3</option>
                <option value='4'>4</option>
                <option value='5'>5</option>
                <option value='6'>6</option>
                <option value='7'>7</option>
                <option value='8'>8</option>
                <option value='9'>9</option>
                <option value='10'>over 9</option>
            </select>
        </div>
    </div>
    <div>
        <header class="">Rooms number</header>
        <div class="select is-small">
            <select class="filter" name="rooms_number" data-field="rooms_number">
                <option value='1'>1</option>
                <option value='2' selected>2</option>
                <option value='3'>3</option>
                <option value='4'>4</option>
                <option value='5'>5</option>
                <option value='6'>6</option>
                <option value='7'>7</option>
                <option value='8'>8</option>
                <option value='9'>9</option>
                <option value='10'>over 9</option>
            </select>
        </div>
    </div>
    <div style="display:inline-block;width:100%">
        <button class="button is-warning pull-right" onclick="updateTable()">Apply</button>
    </div>
</div>

<div class="box">
    <header class=""><strong>Main features</strong></header>
    {% for feature in features %}
    <div class="">
        <input type="checkbox" id="feature_{{ feature.id }}" class="filter"
            data-value="{{ feature.id }}" data-field="feature_{{ feature.id }}"/>
            <label for="feature_{{ feature.id }}">{{ feature }}</label>
    </div>
    {% endfor %}

    <header class=""><strong>Room features</strong></header>
    {% for feature in room_features %}
    <div class="">
        <input type="checkbox" id="room_feature_{{ feature.id }}" class="filter"
            data-value="{{ feature.id }}" data-field="room_feature_{{ feature.id }}"/>
            <label for="room_feature_{{ feature.id }}">{{ feature }}</label>
    </div>
    {% endfor %}

    <header class=""><strong>Ratings</strong></header>
    {% for key, value in ratings %}
    <div class="">
        <input type="checkbox" id="rate_{{ key }}" class="filter"
            data-value="{{ key }}" data-field="rate_{{ key }}"/>
            <label for="rate_{{ key }}">{{ value }}</label>
    </div>
    {% endfor %}

    <div style="display:inline-block;width:100%">
        <button class="button is-warning pull-right" onclick="clearFilters()">Clear</button>
        <button class="button pull-right button-spaced" onclick="updateTable()">Apply</button>
    </div>
</div>

<script>
    $('#id-start-date').datepicker({
        autoclose: true,
        startDate: "today",
    }).on(
        'changeDate', function(e){
            $('#id-end-date').datepicker('setStartDate', e.date);
            var new_date = moment(e.date, "MM/DD/YYYY");
            $('#id-end-date').datepicker('setDate', new_date.add(1, 'days').format("MM/DD/YYYY"));
    });

    $('#id-end-date').datepicker({
        useCurrent: false, //Important! See issue #1075
        autoclose: true,
    });
    //.on(
        //'changeDate', function(e){
        //    $('#id-start-date').datepicker('setEndDate', e.date);
    //});

    $('#id-start-date').datepicker("setDate", new Date());

</script>

{% endif %}

web/templates/customers/_pagin.html
{% if page.paginator.num_pages > 1 %}

<nav class="pagination" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
        {% for p in page.paginator.page_range %}
            {% if p == page.number %}
            <li>
                <a class="pagination-link is-current" data-page="{{ p }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a class="pagination-link" data-page="{{ p }}">{{ p }}</a>
            </li>
            {% endif %}
        {% endfor %}
    </ul>
    <input type="hidden" class="filter change page_filter" data-field="page"></input>
</nav>

{% endif %}

web/templates/customers/_review_details.html
<div class="box">
    <div class="columns">
        <div class="column is-one-quarter">
            <div class="title is-6">{{ review.user.public_name }}</div>
            <div class="title is-6">{{ review.user.country }}</div>
            <div class="subtitle is-6">{{ review.get_type_display }}</div>
            <div class="subtitle is-6">on {{ review.created_at|date:'F Y' }}</div>
        </div>

        <div class="column is-two-thirds">
            <div class="subtitle is-5">
                <div class="icon rate-avg">{{ review.rate }}</div>&nbsp;&nbsp;&nbsp;"{{ review.heading|safe }}"
            </div>
            <div class="subtitle is-6">
                <span class="icon has-text-success fa-lg"><i class="fas fa-plus-square"></i></span>
                {{ review.pros|safe }}
            </div>
            <div class="subtitle is-6">
                <span class="icon has-text-warning fa-lg"><i class="fas fa-minus-square"></i></span>
                {{ review.cons|safe }}
            </div>
        </div>
    </div>
</div>

web/templates/customers/_reviews_list.html
<div class="items-list">

    {% for review in objects %}
        {% include "customers/_review_details.html" %}
    {% endfor %}

</div>

web/templates/customers/files_list.html
{% extends "customers/home.html" %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Files{% endblock %}

{% block left_filters %}
    {{ block.super }}
{% endblock %}

{% block content %}

<div class="files-list-js">
    {% include 'customers/_files_list.html' %}
</div>

<div class="pagin-js">
    {% include 'customers/_pagin.html' %}
</div>

<script>
    listURL="{{ list_url }}";
</script>

{% endblock %}

web/templates/customers/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Customers Login{% endblock %}

{% block container %}

<div class="col-xs-4 col-xs-offset-4">
    <div class="form-label">
        Wellcome!
    </div>
    <form role="form" class="form-horizontal" method="post" action=".">
        {% csrf_token %}

        {% include "common/_form_nf_errors.html" %}

        {% for field in form %}

            {% include "common/_form_field_errors.html" %}

            <div class="form-label">{{ field.label }}</div>
            {{ field|add_class:"form-control" }}

        {% endfor %}

        <input type="submit" class="btn btn-primary btn-container btn-bold" value="Login" />
        <a role="button" class="btn btn-bold btn-default" href="{% url 'fe_home' %}">Back</a>
    </form>
</div>

{% endblock %}

web/templates/customers/make_order2.html
{% extends "customers/home.html" %}

{% load widget_tweaks %}
{% load thumbnail %}

{% block title %}{{ file.name }} Make Order{% endblock %}

{% block content %}

    <div class="steps">
        <div class="step-item is-completed is-success">
            <div class="step-marker">
                <span class="icon">
                    <i class="fa fa-check"></i>
                </span>
            </div>
            <div class="step-details">
                <p class="step-title">Step 1</p>
                <p>Select your room</p>
            </div>
        </div>
        <div class="step-item is-active">
            <div class="step-marker"></div>
            <div class="step-details">
                <p class="step-title">Step 2</p>
                <p>Order details</p>
            </div>
        </div>
        <div class="step-item">
            <div class="step-marker"></div>
            <div class="step-details">
                <p class="step-title">Step 3</p>
                <p>Checkout</p>
            </div>
        </div>
        <div class="step-item">
            <div class="step-marker">
                <span class="icon">
                    <i class="fa fa-flag"></i>
                </span>
            </div>
            <div class="step-details">
                <p class="step-title">Step 4</p>
                <p>Order review</p>
            </div>
        </div>
    </div>

    <div class="box">
        <div class="subtitle"><strong>{{ file }}</strong></div>
        <div class="subtitle">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Room</th>
                        <th>Guests number</th>
                        <th>Price</th>
                    </tr>
                    {% for price in prices %}
                    <tr>
                        <td>{{ price.room_set.first }}</td>
                        <td>{{ price.people_number }}</td>
                        <td>{{ price.price }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="subtitle">Total price: <strong>{{ price }}</strong></div>
    </div>

    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %}

        <div class="field is-grouped">
            <div class="control">
                <label class="label" for="id_title">Title</label>
                <div class="select">
                    {% if form.title.errors %}
                        {{ form.title|add_class:"select"|add_class:"is-danger" }}
                        <p class="help is-danger">{{ form.title.errors.0 }}</p>
                    {% else %}
                        {{ form.title|add_class:"select" }}
                    {% endif %}
                </div>
            </div>
            <div class="control is-expanded">
                <label class="label" for="id_first_name">First Name</label>
                {% if form.first_name.errors %}
                    {{ form.first_name|add_class:"input"|add_class:"is-danger" }}
                    <p class="help is-danger">{{ form.first_name.errors.0 }}</p>
                {% else %}
                    {{ form.first_name|add_class:"input" }}
                {% endif %}
            </div>
            <div class="control is-expanded">
                <label class="label" for="id_last_name">Last Name</label>
                {% if form.last_name.errors %}
                    {{ form.last_name|add_class:"input"|add_class:"is-danger" }}
                    <p class="help is-danger">{{ form.last_name.errors.0 }}</p>
                {% else %}
                    {{ form.last_name|add_class:"input" }}
                {% endif %}
            </div>
        </div>

        <div class="field">
            <div class="control">
                <label class="label" for="id_email">Email Address</label>
                {% if form.email.errors %}
                    {{ form.email|add_class:"input"|add_class:"is-danger" }}
                    <p class="help is-danger">{{ form.email.errors.0 }}</p>
                {% else %}
                    {{ form.email|add_class:"input" }}
                {% endif %}
            </div>
            <div class="control">
                <label class="label" for="id_confirm_email">Confirm Email Address</label>
                {% if form.confirm_email.errors %}
                    {{ form.confirm_email|add_class:"input"|add_class:"is-danger" }}
                    <p class="help is-danger">{{ form.confirm_email.errors.0 }}</p>
                {% else %}
                    {{ form.confirm_email|add_class:"input" }}
                {% endif %}
            </div>
            <div class="control">
                <label class="label" for="id_message">Special Request</label>
                {% if form.message.errors %}
                    {{ form.message|add_class:"textarea"|add_class:"is-danger" }}
                    <p class="help is-danger">{{ form.message.errors.0 }}</p>
                {% else %}
                    {{ form.message|add_class:"textarea" }}
                {% endif %}
            </div>
        </div>

        <input class="button is-info pull-right" type="submit" value="OK" />

    </form>

{% endblock %}

web/templates/customers/make_order3.html
{% extends "customers/home.html" %}

{% load widget_tweaks %}
{% load thumbnail %}

{% block title %}{{ file.name }} Make Order{% endblock %}

{% block content %}

    <div class="box">
        <div class="steps">
            <div class="step-item is-completed is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="fa fa-check"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Step 1</p>
                    <p>Select your room</p>
                </div>
            </div>
            <div class="step-item is-completed is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="fa fa-check"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Step 2</p>
                    <p>Order details</p>
                </div>
            </div>
            <div class="step-item is-active">
                <div class="step-marker"></div>
                <div class="step-details">
                    <p class="step-title">Step 3</p>
                    <p>Checkout</p>
                </div>
            </div>
            <div class="step-item">
                <div class="step-marker">
                    <span class="icon">
                        <i class="fa fa-flag"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Step 4</p>
                    <p>Order review</p>
                </div>
            </div>
        </div>
    </div>

    <div>
        <div class="subtitle">Item: <strong>{{ order.item }}</strong></div>
        <div class="subtitle">Rooms:
            {% for room in order.rooms.all %}
                <strong>{{ room }}</strong>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </div>
        <div class="subtitle">Start date: <strong>{{ order.start_date|date:"M d, Y" }}</strong></div>
        <div class="subtitle">End date: <strong>{{ order.end_date|date:"M d, Y" }}</strong></div>
        <div class="subtitle">First name: <strong>{{ order.first_name }}</strong></div>
        <div class="subtitle">Last name: <strong>{{ order.last_name }}</strong></div>
        <div class="subtitle">Email: <strong>{{ order.email }}</strong></div>
        <div class="subtitle">Message: <strong>{{ order.message }}</strong></div>
        <div class="subtitle">Price: <strong>{{ order.price }}</strong></div>
    </div>

    <div class="subtitle">
        <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post">
            <!-- Identify your business so that you can collect the payments. -->
            <input type="hidden" name="business" value="amigo00678-facilitator@gmail.com">

            <!-- Specify a Buy Now button. -->
            <input type="hidden" name="cmd" value="_xclick">

            <!-- Specify details about the item that buyers will purchase. -->
            <input type="hidden" name="item_name" value="Order-{{ order.id }}">
            <input type="hidden" name="amount" value="{{ order.price }}">
            <input type="hidden" name="currency_code" value="USD">

            <!-- Display the payment button. -->
            <input type="image" name="submit" border="0"
                src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_LG.gif" alt="Buy Now">
            <img alt="" border="0" width="1" height="1"
                src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif">
        </form>
    </div>

{% endblock %}